package com.mertkandemir.bank.dto;

public enum CityDto {
    ADANA, ADIYAMAN, AFYONKARAHİSAR, AĞRI, AKSARAY, AMASYA, ANKARA,
    ANTALYA, ARDAHAN, ARTVİN, AYDIN, BALIKESİR, BARTIN, BATMAN, BAYBURT, BİLECİK, BİNGÖL,
    BİTLİS, BOLU, BURDUR, BURSA, ÇANAKKALE, ÇANKIRI, ÇORUM, DENİZLİ, DİYARBAKIR, DÜZCE, EDİRNE,
    ELAZIĞ, ERZİNCAN, ERZURUM, ESKİŞEHİR,
    GAZİANTEP, GİRESUN, GÜMÜŞHANE, HAKKARİ, HATAY, IĞDIR, İZMİR, ISTANBUL,
    ISPARTA, KAHRAMANMARAŞ, KARABÜK,
    KARAMAN, KARS, KASTAMONU, KAYSERİ, KIRIKKALE, KIRKLARELİ,
    KIRŞEHİR, KİLİS, KOCAELİ, KONYA, KÜTAHYA, MALATYA, MANİSA, MARDİN, MERSİN, MUĞLA, MUŞ,
    NEVŞEHİR, NİĞDE, ORDU, OSMANİYE, RİZE, SAKARYA, SAMSUN, SİİRT, SİNOP, SİVAS, ŞIRNAK,
    TEKİRDAĞ, TOKAT, TRABZON, TUNCELİ, ŞANLIURFA, UŞAK, VAN, YALOVA, YOZGAT, ZONGULDAK
}
